pull_request_rules:
  - name: Automatically merge PRs when CI passes
    conditions:
      - author=liftM
      - status-success=build-run-and-test
    actions:
      merge:
        method: merge
        strict: true
