name: Build, run, and test
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein test

      - name: Solve day 1 challenge
        # We use `jq` workarounds when the input file has multiple lines,
        # because GitHub Actions Secrets swallow newlines.
        run: |
          echo -n $PUZZLE_INPUT_DAY_1 | jq -r . | head -c -1 > /tmp/puzzle-input-day-1
          lein run -- --input-file /tmp/puzzle-input-day-1 --puzzle 1
        env:
          PUZZLE_INPUT_DAY_1: ${{ secrets.PUZZLE_INPUT_DAY_1}}
      - name: Solve day 2 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_2 > /tmp/puzzle-input-day-2
          lein run -- --input-file /tmp/puzzle-input-day-2 --puzzle 2
        env:
          PUZZLE_INPUT_DAY_2: ${{ secrets.PUZZLE_INPUT_DAY_2}}
      - name: Solve day 3 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_3 | jq -r . | head -c -1 > /tmp/puzzle-input-day-3
          lein run -- --input-file /tmp/puzzle-input-day-3 --puzzle 3
        env:
          PUZZLE_INPUT_DAY_3: ${{ secrets.PUZZLE_INPUT_DAY_3}}
      - name: Solve day 4 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_4 > /tmp/puzzle-input-day-4
          lein run -- --input-file /tmp/puzzle-input-day-4 --puzzle 4
        env:
          PUZZLE_INPUT_DAY_4: ${{ secrets.PUZZLE_INPUT_DAY_4}}
      - name: Solve day 5 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_5 > /tmp/puzzle-input-day-5
          lein run -- --input-file /tmp/puzzle-input-day-5 --puzzle 5
        env:
          PUZZLE_INPUT_DAY_5: ${{ secrets.PUZZLE_INPUT_DAY_5}}
      - name: Solve day 6 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_6 | jq -r . | head -c -1 > /tmp/puzzle-input-day-6
          lein run -- --input-file /tmp/puzzle-input-day-6 --puzzle 6
        env:
          PUZZLE_INPUT_DAY_6: ${{ secrets.PUZZLE_INPUT_DAY_6}}
