name: Build, run, and test
on: [push]

jobs:
  build-run-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein test

      - name: Solve day 1 challenge
        # We use `jq` workarounds when the input file has multiple lines,
        # because GitHub Actions Secrets swallow newlines.
        run: |
          echo -n $PUZZLE_INPUT_DAY_1 | jq -r . | head -c -1 > /tmp/puzzle-input-day-1
          lein run -- --input-file /tmp/puzzle-input-day-1 --puzzle 1
        env:
          PUZZLE_INPUT_DAY_1: ${{ secrets.PUZZLE_INPUT_DAY_1}}
      - name: Solve day 2 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_2 > /tmp/puzzle-input-day-2
          lein run -- --input-file /tmp/puzzle-input-day-2 --puzzle 2
        env:
          PUZZLE_INPUT_DAY_2: ${{ secrets.PUZZLE_INPUT_DAY_2}}
      - name: Solve day 3 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_3 | jq -r . | head -c -1 > /tmp/puzzle-input-day-3
          lein run -- --input-file /tmp/puzzle-input-day-3 --puzzle 3
        env:
          PUZZLE_INPUT_DAY_3: ${{ secrets.PUZZLE_INPUT_DAY_3}}
      - name: Solve day 4 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_4 > /tmp/puzzle-input-day-4
          lein run -- --input-file /tmp/puzzle-input-day-4 --puzzle 4
        env:
          PUZZLE_INPUT_DAY_4: ${{ secrets.PUZZLE_INPUT_DAY_4}}
      - name: Solve day 5 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_5 > /tmp/puzzle-input-day-5
          lein run -- --input-file /tmp/puzzle-input-day-5 --puzzle 5
        env:
          PUZZLE_INPUT_DAY_5: ${{ secrets.PUZZLE_INPUT_DAY_5}}
      - name: Solve day 6 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_6 | jq -r . | head -c -1 > /tmp/puzzle-input-day-6
          lein run -- --input-file /tmp/puzzle-input-day-6 --puzzle 6
        env:
          PUZZLE_INPUT_DAY_6: ${{ secrets.PUZZLE_INPUT_DAY_6}}
      - name: Solve day 7 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_7 > /tmp/puzzle-input-day-7
          lein run -- --input-file /tmp/puzzle-input-day-7 --puzzle 7
        env:
          PUZZLE_INPUT_DAY_7: ${{ secrets.PUZZLE_INPUT_DAY_7}}
      - name: Solve day 8 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_8 > /tmp/puzzle-input-day-8
          lein run -- --input-file /tmp/puzzle-input-day-8 --puzzle 8
        env:
          PUZZLE_INPUT_DAY_8: ${{ secrets.PUZZLE_INPUT_DAY_8}}
      - name: Solve day 9 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_9 > /tmp/puzzle-input-day-9
          lein run -- --input-file /tmp/puzzle-input-day-9 --puzzle 9
        env:
          PUZZLE_INPUT_DAY_9: ${{ secrets.PUZZLE_INPUT_DAY_9}}
      - name: Solve day 10 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_10 | jq -r . | head -c -1 > /tmp/puzzle-input-day-10
          lein run -- --input-file /tmp/puzzle-input-day-10 --puzzle 10
        env:
          PUZZLE_INPUT_DAY_10: ${{ secrets.PUZZLE_INPUT_DAY_10}}
      - name: Solve day 11 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_11 > /tmp/puzzle-input-day-11
          lein run -- --input-file /tmp/puzzle-input-day-11 --puzzle 11
        env:
          PUZZLE_INPUT_DAY_11: ${{ secrets.PUZZLE_INPUT_DAY_11}}
      - name: Solve day 12 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_12 | jq -r . | head -c -1 > /tmp/puzzle-input-day-12
          lein run -- --input-file /tmp/puzzle-input-day-12 --puzzle 12
        env:
          PUZZLE_INPUT_DAY_12: ${{ secrets.PUZZLE_INPUT_DAY_12}}
      - name: Solve day 13 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_13 > /tmp/puzzle-input-day-13
          lein run -- --input-file /tmp/puzzle-input-day-13 --puzzle 13
        env:
          PUZZLE_INPUT_DAY_13: ${{ secrets.PUZZLE_INPUT_DAY_13}}
      - name: Solve day 14 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_14 | jq -r . | head -c -1 > /tmp/puzzle-input-day-14
          lein run -- --input-file /tmp/puzzle-input-day-14 --puzzle 14
        env:
          PUZZLE_INPUT_DAY_14: ${{ secrets.PUZZLE_INPUT_DAY_14}}
      - name: Solve day 15 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_15 > /tmp/puzzle-input-day-15
          lein run -- --input-file /tmp/puzzle-input-day-15 --puzzle 15
        env:
          PUZZLE_INPUT_DAY_15: ${{ secrets.PUZZLE_INPUT_DAY_15}}
      - name: Solve day 16 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_16 > /tmp/puzzle-input-day-16
          lein run -- --input-file /tmp/puzzle-input-day-16 --puzzle 16
        env:
          PUZZLE_INPUT_DAY_16: ${{ secrets.PUZZLE_INPUT_DAY_16}}
      - name: Solve day 17 challenge
        run: |
          echo -n $PUZZLE_INPUT_DAY_17 > /tmp/puzzle-input-day-17
          lein run -- --input-file /tmp/puzzle-input-day-17 --puzzle 17
        env:
          PUZZLE_INPUT_DAY_17: ${{ secrets.PUZZLE_INPUT_DAY_17}}
